language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
dist: xenial
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      env: OCAML_VERSION=4.09
    - os: freebsd
      env: OCAML_VERSION=4.09
    - os: linux
      arch: amd64
      env: OCAML_VERSION=4.09 INSTALL_LOCAL=1
    - os: linux
      arch: amd64
      env: OCAML_VERSION=4.10
    - os: linux
      arch: arm64
      env: OCAML_VERSION=4.11
notifications:
  email:
  - opam-commits@lists.ocaml.org
  irc:
  - chat.freenode.net#opam
